### ISSUE TITLE
[Timer] Back Press error

### ISSUE THREAD

**Issue by snowflake-1117** [lynring24/ITimeU#36]
백 버튼을 누를 시 finish 처리는 되었지만, 아래의 에러가 발생합니다.

```logcat
09-04 15:16:07.243 12877-12877/com.itti7.itimeu E/ActivityThread: Activity com.itti7.itimeu.MainActivity has leaked ServiceConnection com.itti7.itimeu.TimerFragment$2@3a90c87 that was originally bound here
                                                                  android.app.ServiceConnectionLeaked: Activity com.itti7.itimeu.MainActivity has leaked ServiceConnection com.itti7.itimeu.TimerFragment$2@3a90c87 that was originally bound here
                                                                      at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
                                                                      at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
                                                                      at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1478)
                                                                      at android.app.ContextImpl.bindService(ContextImpl.java:1450)
                                                                      at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
                                                                      at com.itti7.itimeu.TimerFragment.onStart(TimerFragment.java:191)
                                                                      at android.support.v4.app.Fragment.performStart(Fragment.java:2265)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1369)
                                                                      at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:1161)
                                                                      at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1678)
                                                                      at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:462)
                                                                      at android.support.v4.content.Loader.deliverResult(Loader.java:126)
                                                                      at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
                                                                      at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
                                                                      at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:252)
                                                                      at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
                                                                      at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:485)
                                                                      at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:502)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
09-04 15:16:07.253 12877-12877/com.itti7.itimeu I/Timer: ------------------------------------------------------->TimeronUnbind
09-04 15:16:07.253 12877-12877/com.itti7.itimeu I/Timer: ------------------------------------------------------->Timer stopTimer
09-04 15:16:07.253 12877-12877/com.itti7.itimeu D/AndroidRuntime: Shutting down VM
09-04 15:16:07.254 12877-12877/com.itti7.itimeu E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.itti7.itimeu, PID: 12877
                                                                  java.lang.RuntimeException: Unable to unbind to service com.itti7.itimeu.TimerService@a77408b with Intent { cmp=com.itti7.itimeu/.TimerService }: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.CountDownTimer.cancel()' on a null object reference
                                                                      at android.app.ActivityThread.handleUnbindService(ActivityThread.java:3231)
                                                                      at android.app.ActivityThread.-wrap28(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1560)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.CountDownTimer.cancel()' on a null object reference
                                                                      at com.itti7.itimeu.TimerService.stopTimer(TimerService.java:105)
                                                                      at com.itti7.itimeu.TimerService.onUnbind(TimerService.java:112)
                                                                      at android.app.ActivityThread.handleUnbindService(ActivityThread.java:3217)
                                                                      at android.app.ActivityThread.-wrap28(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1560) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 

```

**Comment by lynring24** [comment]
back 버튼이랑 홈버튼 디자인이 필요한데
+ back : stop 
+ home : stop으로 하고 있는데 사실 background로 돌리고 있는 부분을 부를 수 있다.

**Comment by snowflake-1117** [comment]
back 이랑 home 버튼 디자인은 왜 필요한거야?ㅁ? 그냥 하단 바에서 접근할수있지 않아?

**Comment by lynring24** [comment]
물리 키는 이벤트 처리를 해줘야 service 에서 발생하는 에러를 치울수 있어 
UI 디자인 말고

**Comment by lynring24** [comment]
지금 처리하려는데 저 부분에 대한 논의는 없었어서

**Comment by snowflake-1117** [comment]
만약 앱 닫고도 돌릴수 있다면 백그라운드로 돌릴듯 stop은 상태바 접근해서 할수 있으니까. 그 기능이 안된다면 stop 하는게 맞겠지?

**Comment by lynring24** [comment]
내가 지금 이해가 안가서 음 그러니까 
if (home) -> works background ( actually stops the activity but could be called again) 
if (back ) -> totally stops

**Comment by lynring24** [comment]
물리키로 접근했을 때  null exception이 생겨서 지금 확인하고 있지만 혹시나 event 처리를 해야하는경우에 저런 액션?기능을 처리하는지 확인해보는 중이야

**Comment by snowflake-1117** [comment]
아 그러니까 
1) 만약 홈버튼을 누르면 시간은 초기화되고 현재 상태만 저장되는 건가?
2) 뒤로가기를 누르면 아예 끝난다는 의미인?

**Comment by lynring24** [comment]
timer fragment 
+ back button evernt 
-> 중단 되었을 때 status = TODO
